apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-calculator
  labels:
    app: bmi-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bmi-calculator
  template:
    metadata:
      labels:
        app: bmi-calculator
    spec:
      containers:
      - name: bmi-calculator
        image: bmi-calculator:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"