name: BMI Calculator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Add caching for faster builds

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run pytest tests
      run: pytest -v --cov=. --cov-report=xml  # Add coverage reporting

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()  # Only run if tests pass

    - name: Run unittest tests
      run: python -m unittest discover -v  # Run unittest tests too

